version: "3.1"
services:
    java:
        container_name: java_app
        build: .docker/
        working_dir: /application
        volumes:
            - .:/application
        read_only: false
        privileged: true
        tty: true
    webserver:
        container_name: web_app
        image: nginx
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
           - 8080:80
        restart: always
        depends_on:
            - java
            - database
    database:
        container_name: db_app
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        image: mysql:8.0.17
        environment:
          MYSQL_ROOT_PASSWORD: 123321 
          MYSQL_DATABASE: testapp
        ports:
          - "3306:3306"
