# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
        ports:
            - "${APP_PORT:-8080}:8080"
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bbgh?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
            SPRING_DATASOURCE_USERNAME: bbgh
            SPRING_DATASOURCE_PASSWORD: bbgh
        command: java -jar /app.jar
    db:
        image: mysql
        ports:
            - "${DB_PORT:-3307}:3306"
        environment:
            MYSQL_DATABASE: bbgh
            MYSQL_USER: bbgh
            MYSQL_PASSWORD: bbgh
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
